# -*- coding: utf-8 -*-
"""
Données des lignes urbaines Dakar Dem Dikk.
Source : https://demdikk.sn/reseau-urbain-dakar/
"""

URBAN_LINES = [
    # ── LIGNES URBAINES ───────────────────────────────────────────────────────
    {
        "number": "1", "start": "Parcelles Assainies", "end": "Place Leclerc",
        "category": "urbaine",
        "stops": [
            "Terminus Parcelles Assainies", "Sapeur Pompiers", "Unités 09 10 15",
            "Ecole Dior", "Terrain Acapes", "Unités 22 24", "Marché Grand Médine",
            "Rond point 26", "VDN-Foire", "Cité Keur Gorgui", "Ecole Normale",
            "Ucad", "Rond point Sham", "Marché Tilène", "Poste Médina", "Difoncé",
            "Sandaga", "Avenue George Pompidou", "Place de l'Indépendance",
            "Gare TER", "Embarcadère", "Terminus Leclerc",
        ],
    },
    {
        "number": "4", "start": "Liberté 5", "end": "Place Leclerc",
        "category": "urbaine",
        "stops": [
            "Terminus Liberté 5 (Dieuppeul)", "Cité Derklé", "Rond point Liberté 6",
            "Khar Yalla", "Cité Marine", "CEM Dieuppeul 3",
            "Eglise Martyrs de l'Ouganda", "SDE", "Collège Sacré Cœur",
            "Sicap Karack", "Point E", "Université Amphate BA", "Canal 4",
            "Marché Fass", "Gueule Tapée", "Rond Point Sham", "Marché Tilène",
            "Poste Médina", "Difoncé", "Sandaga", "ASECNA",
            "Boulevard de la République", "Avenue Léopold Sédar Senghor",
            "Place de l'Indépendance", "Gare TER", "Embarcadère", "Terminus Leclerc",
        ],
    },
    {
        "number": "7", "start": "Ouakam", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus Ouakam", "Cité Assemblée", "Cité Comico", "Sortie Ouakam",
            "Hopital IHO", "Mermoz", "ENEA", "Ecole Normale", "UCAD",
            "Rond point Sham", "Marché Tilène", "Poste Médina", "Difoncé",
            "Sandaga", "Avenue George Pompidou", "Place de l'Indépendance",
            "Avenue Léopold Sédar Senghor", "Hôpital Principale",
            "Rond point Assemblée Nationale", "Institut Pasteur", "Terminus Palais 2",
        ],
    },
    {
        "number": "8", "start": "Aéroport LSS", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus Aéroport LSS", "Cité Asecna", "Yoff Village", "Pond Foire",
            "Stade Léopold Sédar Senghor – Patte d'Oie", "Grand Yoff",
            "Hôpital Général Idrissa Pouye (Ex CTO)", "Cité des Eaux",
            "Station Castor", "Avenue Bourguiba", "Jet d'eau", "Stade Demba Diop",
            "Dial Diop", "Zone B", "Point E", "UCAD", "Rond point Sham",
            "Marché Tilène", "Poste Médina", "Difoncé", "Sandaga", "ASECNA",
            "Bld de la République", "Avenue Léopold Sédar Senghor",
            "Hôpital Principale", "Rond point Assemblée Nationale",
            "Institut Pasteur", "Terminus Palais 2",
        ],
    },
    {
        "number": "9", "start": "Liberté 6", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus Liberté 6", "Rond Point JVC", "Sacré Cœur", "IPG",
            "Terminus Dieuppeul", "Allées Ababacar Sy", "Rond Point Jet d'Eau",
            "Niary Tally", "Eglise Sainte Thérèse", "Lycée Blaise Diagne",
            "Lycée Kennedy", "Obélisque", "Centenaire", "Rond point RTS",
            "Poste Médina", "Difoncé", "Sandaga", "Avenue George Pompidou",
            "Place de l'Indépendance", "Avenue Léopold Sédar Senghor",
            "Hôpital Principale", "Rond point Assemblée Nationale",
            "Institut Pasteur", "Terminus Palais 2",
        ],
    },
    {
        "number": "10", "start": "Liberté 5", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus Liberté 5 (Dieuppeul)", "Cité Derklé", "Rond point Liberté 6",
            "Khar Yalla", "Cité Marine", "CEM Ousmane Socé Diop",
            "Eglise Martyrs de l'Ouganda", "SDE", "Dakar Sacré Cœur",
            "Stade Demba Diop", "Avenue Bourguiba", "Ecole Normale", "Poste Fann",
            "Rue Aimé Césaire", "Ministère de la Santé", "Corniche Ouest", "IFAN",
            "Hotel Terrou", "Tunnel de Soumbédioune", "Village Artisanal",
            "Prison Rebeuss", "Tribunal de Dakar", "Boulevard de la République",
            "Sorano", "Avenue Léopold Sédar Senghor", "Hôpital Principale",
            "Rond point Assemblée Nationale", "Institut Pasteur", "Terminus Palais 2",
        ],
    },
    {
        "number": "13", "start": "Liberté 5", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus Liberté 5 (Dieuppeul)", "Avenue Cheikh Ahmadou Bamba",
            "Station Castors", "Marché HLM", "Ouagou Niayes", "BOP",
            "Masalikul Djinane", "CSS", "Lycée Kennedy",
            "Boulevard Général De Gaulle", "Centenaire", "RTS", "Grande Mosquée",
            "Allées Papa Guèye Fall", "Petersen", "Avenue Faidherbe", "Esso Port",
            "Gare de Dakar", "Place de l'Indépendance",
            "Avenue Léopold Sédar Senghor", "Hôpital Principale",
            "Rond point Assemblée Nationale", "Institut Pasteur", "Terminus Palais 2",
        ],
    },
    {
        "number": "18", "start": "Dieuppeul", "end": "Dieuppeul (boucle)",
        "category": "urbaine",
        "stops": [
            "Terminus Liberté 5 (Dieuppeul)", "Cité Derklé", "Rond Point Liberté 6",
            "Khar Yalla", "Cité Marine", "Avenue Cheikh Ahmadou Bamba",
            "Station Castors", "Marché HLM", "Ouagou Niayes", "BOP",
            "Masalikul Djinane", "CSS", "Colobane", "Service des Mines",
            "Place Bakou", "Police Bel Air", "Grand Moulin de Dakar", "Bel Air",
            "Arsenal", "Gare de Dakar", "Esso Port", "Place de l'Indépendance",
            "Avenue Georges Pompidou", "Rond point Sandaga", "Avenue André Peytavin",
            "Lat Dior", "Rebeuss", "Mosquée Seydou Nourrou Tall",
            "Rue 6", "Médina", "Gueule Tapée", "Lycée Delafosse", "Canal 4",
            "Rond point Sham", "Avenue Cheikh Anta Diop", "Ecole Normale Supérieure",
            "Avenue Bourguiba", "Stade Demba Diop", "Rond Point Jet d'eau",
            "Allées Ababacar Sy", "Terminus Liberté 5 (Dieuppeul)",
        ],
    },
    {
        "number": "20", "start": "Dieuppeul", "end": "Dieuppeul (boucle)",
        "category": "urbaine",
        "stops": [
            "Terminus Dieuppeul", "Allées Ababacar Sy", "Jet d'Eau",
            "Avenue Bourguiba", "Stade Demba Diop", "Ecole Normale", "Poste Fann",
            "Avenue Cheikh Anta Diop", "UCAD", "Canal 4", "Lycée Delafosse",
            "Gueule Tapée", "Rue 6", "Médina", "DAF",
            "Mosquée Seydou Nourrou Tall", "Rebeuss", "Lat Dior",
            "Avenue Peytavin", "Rond point Sandaga", "Avenue Georges Pompidou",
            "Place de l'Indépendance", "Gare TER", "Esso Port",
            "Boulevard de l'Arsenal", "Central Bel Air", "Grand Moulin de Dakar",
            "Police Bel Air", "Service des Mines", "Colobane", "CSS",
            "Masalikul Djinane", "Cité Port", "Ouagou Niayes", "Marché HLM",
            "Station Castors", "Avenue Cheikh Ahmadou Bamba", "Cité Marine",
            "Khar Yalla", "Rond Point Liberté 6", "Cité Derklé", "Terminus Dieuppeul",
        ],
    },
    {
        "number": "23", "start": "Parcelles Assainies", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus des Parcelles", "Ecole Dior", "Diamalaye", "HLM Grand Médine",
            "Dior", "Acapes", "Dispensaire Norade", "Hôpital Mame Abdou", "Eglise",
            "Unité 11", "Croisement 22", "Police Parcelles", "Pont Émergent",
            "Ecole Hyacinthe Thiandoum", "Rond point Liberté 6", "Khar Yalla",
            "Front de Terre", "Cité des Eaux", "Station Castor", "Avenue Bourguiba",
            "Stade Demba Diop", "Ecole Normale", "Poste Fann",
            "Avenue Cheikh Anta Diop", "UCAD", "Rond Point Sham", "Canal 4",
            "Gueule Tapée", "Rue 6", "DAF", "Poste Médina", "Difoncé", "Sandaga",
            "ASECNA", "Bld de la République", "Avenue Léopold Sédar Senghor",
            "Hôpital Principale", "Rond point Assemblée Nationale",
            "Institut Pasteur", "Terminus Palais 2",
        ],
    },
    {
        "number": "121", "start": "Scat Urbam", "end": "Leclerc",
        "category": "urbaine",
        "stops": [
            "Terminus Scat Urbam", "Mairie Grand Yoff", "Pentola",
            "Les deux voies de Sipres", "Camp Pénal", "Les deux voies de Liberté 6",
            "Rond point JVC", "Boulangerie Zone", "Collège Sacré Cœur",
            "Scor Liberté", "Sicap Rue 10", "Lycée Blaise Diagne", "Place ONU",
            "Canal 4", "HLM Fass", "Travaux Communaux", "Rue 22 Prolongée", "RTS",
            "Allées Papa Guèye Fall", "Petersen", "Avenue Faidherbe",
            "Place de l'Indépendance", "Albert Sarraut", "BCEAO", "Terminus Leclerc",
        ],
    },
    {
        "number": "319", "start": "Liberté 6", "end": "Ouakam",
        "category": "urbaine",
        "stops": [
            "Terminus Liberté 6", "Rond Point Liberté 6", "Deux voies Liberté 6",
            "Rond point JVC", "Boulangerie Jaune", "Immeuble Mariama",
            "Rond point Cheikh Bethio", "Ancienne Piste", "IHO", "Entrée Ouakam",
            "Pharmacie Cité Aviation", "Pharmacie Mame Seynabou",
            "Case des Tout Petits", "Station Shell",
            "Lycée d'Excellence Privée", "Boulangerie N'Wely", "Terminus Ouakam",
        ],
    },
    {
        "number": "TO1", "start": "Ouakam", "end": "Palais 2",
        "category": "urbaine",
        "stops": [
            "Terminus Ouakam", "Brioche Dorée Ouakam",
            "Monument de la Renaissance", "Corniche Ouest", "Avenue Peytavin",
            "Avenue Pompidou", "Place de l'Indépendance",
            "Avenue Léopold Sédar Senghor", "Avenue Nelson Mandela", "Palais 2",
        ],
    },
    {
        "number": "501", "start": "Palais 2", "end": "Leclerc",
        "category": "urbaine",
        "stops": [
            "Terminus Palais 2", "Avenue Nelson Mandela",
            "Avenue Léopold Sédar Senghor", "Place de l'Indépendance",
            "Esso Port Embarcadère", "Terminus Leclerc",
        ],
    },
    {
        "number": "502", "start": "Gare Colobane", "end": "Gare Colobane (boucle)",
        "category": "urbaine",
        "stops": [
            "Gare Colobane", "Maison du Parti", "Hampathé Ba", "UCAD",
            "Lycée De Lafosse", "Police 4ème", "Rond Point Sham", "Gare Colobane",
        ],
    },
    {
        "number": "503", "start": "Gare Colobane", "end": "Gare Colobane (boucle)",
        "category": "urbaine",
        "stops": [
            "Gare de Colobane", "Rond Point Bel Air", "Môle 8", "Cité Isra",
            "Zone Industrielle", "Service des Mines", "Gare de Colobane",
        ],
    },
    {
        "number": "TAF TAF", "start": "Ouakam", "end": "AIBD",
        "category": "urbaine",
        "stops": [
            "Terminus Ouakam", "Mamelles", "Croisement Almadies", "Ngor", "Yoff",
            "Route de l'Aéroport", "Foire", "VDN", "Direction Générale DDD",
            "Rond Point JVC", "Rond Point Liberté 6", "Itinéraire 213",
            "Police Grand Yoff", "Pharmacie Patte d'Oie", "Autoroute à Péage",
            "Diamniadio", "AIBD",
        ],
    },
    # ── LIGNES BANLIEUE ───────────────────────────────────────────────────────
    {
        "number": "2", "start": "Daroukhane", "end": "Place Leclerc",
        "category": "banlieue",
        "stops": [
            "Terminus Daroukhane", "Corniche", "Hamo", "Terminus Guédiawaye",
            "Marché Sahm", "Ravin", "Ecole Canada", "Route des Niayes",
            "Tally Boumack", "Bountou Pikine", "Route Nationale n°1",
            "Péage Pikine", "Cité des Eaux", "Station Castors",
            "Avenue Cheikh Ahmadou Bamba", "Marché HLM", "Masalikul Djinane",
            "BOPP", "Rond Point Colobane", "Lycée Kennedy",
            "Boulevard Général De Gaulle", "Obélisque", "Rue 39", "Douta Seck",
            "Avenue Blaise Diagne", "Poste Médina", "Difoncé", "Sandaga", "ASECNA",
            "Boulevard de la République", "Avenue Léopold Sédar Senghor",
            "Place de l'Indépendance", "Gare de Dakar", "Embarcadère",
            "Terminus Leclerc",
        ],
    },
    {
        "number": "5", "start": "Guédiawaye", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Terminus Guédiawaye", "Marché Jeudi", "Hôpital Dalal Diam",
            "Case PA", "Police Parcelles Assainies",
            "Pont Sénégal 92 (Pont de l'Émergence)", "Patte d'Oie", "Autoroute",
            "Intendance", "Avenue Lamine Guèye", "Avenue André Peytavin",
            "Avenue Jean Jaurès", "Boulevard de la République",
            "Avenue Léopold Sédar Senghor", "Avenue Nelson Mandela", "Palais 1",
        ],
    },
    {
        "number": "6", "start": "Guédiawaye", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Terminus Guédiawaye", "Marché Jeudi", "Hôpital Dalal Diam",
            "Cambérène", "Case PA", "Police Parcelles Assainies",
            "Marché Grand Médine", "Rond point 26", "Foire", "Sipres",
            "Rond point Liberté 6", "Terminus Liberté 5",
            "Allées Khalifa Ababacar Sy", "Jet d'Eau", "Niary Tally",
            "Eglise Sainte Thérèse", "ENA", "Boulevard Général De Gaulle",
            "Allées Papa Guèye Fall", "Avenue Faidherbe", "Avenue Lamine Guèye",
            "Avenue André Peytavin", "Avenue Jean Jaurès",
            "Boulevard de la République", "Avenue Nelson Mandela", "Palais 1",
        ],
    },
    {
        "number": "11", "start": "Keur Massar", "end": "Lat Dior",
        "category": "banlieue",
        "stops": [
            "Terminus Keur Massar", "Station Keur Massar",
            "Croisement Keur Massar", "Fass Mbao", "Diamaguène",
            "Poste Thiaroye", "Autoroute à Péage",
            "Corniche des HLM", "Colobane",
            "Boulevard Général De Gaulle (Centenaire)", "RTS", "Rond Point",
            "Poste Médina", "Blaise Diagne", "Sandaga", "Terminus Lat Dior",
        ],
    },
    {
        "number": "12", "start": "Guédiawaye", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Terminus Guédiawaye", "Lycée Canada", "Tally Boubess",
            "Marché Sandika", "Bountou Pikine", "National 1",
            "Croisement Cambérène", "Autoroute", "Cité des Eaux",
            "Station Castors", "Avenue Bourguiba", "Ecole Normale",
            "Avenue Cheikh Anta Diop (Hôpital Fann)", "Rond Point Sham",
            "Avenue Blaise Diagne", "Avenue Jean Jaurès",
            "Boulevard de la République", "Avenue Léopold Sédar Senghor",
            "Avenue Nelson Mandela", "Palais 1",
        ],
    },
    {
        "number": "15", "start": "Rufisque", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Terminus Rufisque", "Djoutiba", "Sortie Rufisque",
            "Croisement Keur Massar", "Fass Mbao", "Diamaguène",
            "Poste Thiaroye", "Croisement Bountou Pikine", "National 1",
            "Croisement Cambérène", "Autoroute", "Colobane", "SCOA",
            "Esso Port", "Place de l'Indépendance",
            "Avenue Léopold Sédar Senghor", "Avenue Nelson Mandela", "Palais 1",
        ],
    },
    {
        "number": "16A", "start": "Malika", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Terminus Malika", "Malika Plage", "Terminus 221 (Gadaye)", "Hamo",
            "Terminus Guédiawaye", "Marché Sahm", "Ecole Canada", "Icotaf",
            "Cité Lobatt Fall", "Rond Point Lobatt Fall", "Autoroute", "Colobane",
            "Rond Point Colobane", "Place Bakou", "Cfao Technologies", "Cyrnos",
            "Arsenal", "Place de l'Indépendance", "Palais 1",
        ],
    },
    {
        "number": "16B", "start": "Malika", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Terminus Malika", "Station Keur Massar", "Croisement Keur Massar",
            "LGI Mbao", "Diamaguène", "Thiaroye", "Sips", "Sotiba (Seras)",
            "Yarakh", "Capa Virmaud", "Place Bakou", "SCOA", "Police Bel Air",
            "Bel Air", "Grand Moulin de Dakar", "Sofrigal (Môle 8)",
            "Cyrnos (sur le pont)", "Caserne Sapeurs Pompiers",
            "Avenue Lamine Guèye (Sandaga)", "Avenue André Peytavin",
            "Avenue Jean Jaurès", "Boulevard de la République",
            "Avenue Léopold Sédar Senghor (Roume)", "Hôpital Principal",
            "Assemblée Nationale", "Hôpital Le Dantec", "Palais 1",
        ],
    },
    {
        "number": "208", "start": "Bayakh", "end": "Rufisque",
        "category": "banlieue",
        "stops": [
            "Gorom 01", "Gorom 02", "Bambilor", "Noflaye",
            "Sangalkam", "Keur Ndiaye Lo", "Rufisque",
        ],
    },
    {
        "number": "213", "start": "Rufisque", "end": "Dieuppeul",
        "category": "banlieue",
        "stops": [
            "Gare de Rufisque", "HLM SIPRES", "ZAC Mbao",
            "Rond Point Grand Mbao", "Keur Mbaye Fall",
            "Croisement Petit Mbao", "Diamaguène", "Poste Thiaroye", "Péage",
            "Sortie Croisement Cambérène", "Patte d'Oie", "Marché Grand Yoff",
            "Police Grand Yoff", "Rond Point Liberté 6",
            "2 voies Liberté 6", "Rond Point JVC", "Terminus Dieuppeul",
        ],
    },
    {
        "number": "217", "start": "Thiaroye", "end": "Aéroport LSS",
        "category": "banlieue",
        "stops": [
            "Dépôt Thiaroye", "Sipses", "Bountou Pikine", "Patte d'Oie", "Foire",
            "VDN", "Sipres", "Ancienne Piste", "Ouakam", "Marché Ouakam",
            "Terminus Ouakam", "Route des Mamelles", "Route des Almadies",
            "Ngor", "Terminus Aéroport LSS",
        ],
    },
    {
        "number": "218", "start": "Thiaroye", "end": "Aéroport LSS",
        "category": "banlieue",
        "stops": [
            "Dépôt Thiaroye", "Sipses", "Bountou Pikine", "Patte d'Oie", "Foire",
            "VDN", "Sipres", "Ancienne Piste", "Ouakam", "Marché Ouakam",
            "Terminus Ouakam", "Route des Mamelles", "Route des Almadies",
            "Ngor", "Terminus Aéroport LSS",
        ],
    },
    {
        "number": "219", "start": "Daroukhane", "end": "Ouakam",
        "category": "banlieue",
        "stops": [
            "Daroukhane", "Marché Ndiarème", "Deux voies Notaire",
            "Sapeur Pompier Guédiawaye", "Marché Jeudi Corniche",
            "Hôpital Dalal Diam", "Case Bi", "Pont Sénégal 92",
            "Collège Hyacinthe Thiandoum", "Rond Point Liberté 6",
            "Rond Point JVC", "Rond Point Boulangerie Jaune", "Immeuble Mariama",
            "Ancienne Piste", "Hôpital Militaire de Ouakam", "Comico",
            "Cité Asecna", "Cité Assemblée", "Terminus Ouakam",
        ],
    },
    {
        "number": "220", "start": "Rufisque", "end": "Guédiawaye",
        "category": "banlieue",
        "stops": [
            "Terminus Rufisque", "Djoutiba", "HLM Rufisque", "SIPRES", "SEDIMA",
            "Lycée Jaxaay", "2 voies", "Jaxaay", "Station Keur Massar",
            "Terminus Malika", "Malika Plage", "Gadaye", "Serigne Assane",
            "Marché Boubess", "Lycée Limamoulaye", "Terminus Guédiawaye",
        ],
    },
    {
        "number": "221", "start": "Gadaye", "end": "Almadies",
        "category": "banlieue",
        "stops": [
            "Terminus Gadaye (Filaos)", "Corniche Daroukhane", "Hamo 6",
            "Arrêt Dial Mbaye", "PAI", "Hôpital Dalal Diam", "Case",
            "Police PA", "Pont Sénégal Émergent (92)", "Route de l'Aéroport",
            "Yoff Tonghor", "Cité Asecna", "Rond Point Ngor", "Ngor Village",
            "Terminus Almadies",
        ],
    },
    {
        "number": "227", "start": "Keur Massar", "end": "Terminus Parcelles",
        "category": "banlieue",
        "stops": [
            "Terminus Keur Massar", "Tolou Abdoulaye Wade",
            "Croisement Tivaoune Peulh", "APIX", "Malika Plage",
            "Police Wakhinane", "Hamo 6", "Arrêt Dial Mbaye",
            "Terminus Guédiawaye", "Stade Amadou Barry", "CES Canada",
            "Hôpital Dalal Diam", "Case Bi", "Croisement 22", "Eglise PA",
            "Terminus Parcelles",
        ],
    },
    {
        "number": "232", "start": "Baux Maraîchers", "end": "Aéroport LSS",
        "category": "banlieue",
        "stops": [
            "Baux Maraîchers", "Yarakh", "Cafétéria", "Hann Maristes",
            "Cours Sainte Marie de Hann", "Sortie Mariste", "Usine des Eaux",
            "Front de Terre", "Khar Yalla", "Rond Point Liberté 6",
            "Deux voies vers Camp Leclerc", "VDN", "Foire", "Yoff",
            "Terminus Aéroport LSS",
        ],
    },
    {
        "number": "233", "start": "Baux Maraîchers", "end": "Palais 1",
        "category": "banlieue",
        "stops": [
            "Baux Maraîchers", "Yarakh", "Cafétéria", "Hann Maristes",
            "Cours Sainte Marie de Hann", "Sortie Mariste", "Usine des Eaux",
            "Front de Terre", "Khar Yalla", "Rond Point Liberté 6",
            "Deux voies vers Camp Leclerc", "VDN", "Foire", "Yoff",
            "Terminus Aéroport LSS",
        ],
    },
    {
        "number": "234", "start": "Jaxaay", "end": "Leclerc",
        "category": "banlieue",
        "stops": [
            "Terminus Jaxaay (Mosquée Niakoul Rab)", "Terminus 56",
            "2 voies Jaxaay", "Station Keur Massar", "Croisement Keur Massar",
            "Fass Mbao", "Diamaguène", "Poste Thiaroye", "Péage",
            "Grand Théâtre", "Esso Port",
            "Place de l'Indépendance – Avenue Sarraut", "Leclerc",
        ],
    },
    {
        "number": "311", "start": "Lac Rose", "end": "Croisement Keur Massar",
        "category": "banlieue",
        "stops": [
            "Lac Rose Croisement Niague", "Croisement Tivaoune Peulh",
            "Terminus Keur Massar", "Station Keur Massar",
            "Croisement Keur Massar", "Retour vers Lac Rose",
        ],
    },
    {
        "number": "327", "start": "Keur Massar", "end": "Terminus Parcelles",
        "category": "banlieue",
        "stops": [
            "Terminus Keur Massar", "Tolou Abdoulaye Wade",
            "Croisement Tivaoune Peulh", "APIX", "Malika Plage", "Malibu",
            "Hôpital Dalal Diam", "Case Bi", "Croisement 22",
            "Eglise PA", "Terminus Parcelles",
        ],
    },
    {
        "number": "RUFISQUE–YENNE", "start": "Rufisque", "end": "Yenne",
        "category": "banlieue",
        "stops": ["Terminus Rufisque", "Ville de Rufisque", "Bargny", "Diamniadio", "Yenne"],
    },
]
